In [1]:
a=[1,2,3]

In [2]:
import numpy as np

In [9]:
arr =np.array(a)
arr

array([1, 2, 3])

In [5]:
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
mat = np.array(mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(0,7)

array([0, 1, 2, 3, 4, 5, 6])

In [18]:
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
np.random.randint(4,73,25)
a

array([41, 14, 18, 43, 12, 44, 29, 49, 43, 39, 70, 40, 16, 57, 72,  5, 51,
       63, 69, 39, 32, 41, 41, 40, 48])

In [29]:
a.reshape(5,5)

array([[51, 12, 37, 43, 25],
       [71, 50, 15, 68, 48],
       [18, 68, 57,  7, 23],
       [56, 55, 51, 49, 29],
       [10, 49, 11, 41, 59]])

In [30]:
a.max()

71

In [38]:
ar=np.arange(0,25)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ar.reshape(5,5)   

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ar.argmax()

24

In [1]:
import numpy as np

In [2]:
a=[1,2]
x=np.array(a)

In [3]:
x

array([1, 2])

In [4]:
y=x
y

array([1, 2])

In [5]:
y[0]=10
y

array([10,  2])

In [6]:
x

array([10,  2])